
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bdg.iapetos.foundary-cloud.io
  resources:
  - statefulpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bdg.iapetos.foundary-cloud.io
  resources:
  - statefulpods/status
  verbs:
  - get
  - patch
  - update
