# permissions for end users to view statefulpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statefulpod-viewer-role
rules:
- apiGroups:
  - bdg.iapetos.foundary-cloud.io
  resources:
  - statefulpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bdg.iapetos.foundary-cloud.io
  resources:
  - statefulpods/status
  verbs:
  - get
