apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-pod
  namespace: statefulpod
  labels:
    app.kubernetes.io/name: stateful-pod
    app.kubernetes.io/version: v2
    app.kubernetes.io/component: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stateful-pod
      app.kubernetes.io/version: v2
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stateful-pod
        app.kubernetes.io/version: v2
        app.kubernetes.io/component: operator
    spec:
      serviceAccountName: stateful-pod-sa
      containers:
        - name: stateful-pod
          image: uhub.service.ucloud.cn/infra/statefulpod:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080



