apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stateful-pod-bind
subjects:
- kind: ServiceAccount
  name: stateful-pod-sa
  namespace: statefulpod
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stateful-pod-sa
  namespace: statefulpod
automountServiceAccountToken: true
