apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cockroach-database-sa-bind
subjects:
- kind: ServiceAccount
  name: cockroach-database-sa
  namespace: ldy
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cockroach-database-sa
  namespace: ldy
automountServiceAccountToken: true
